#+TITLE: Schedulers

This document lists different type of network schedulers and their attributes.

* Schedulers
** [X] Calendar Queues
*** The Calendar Queue is a programmable scheduler that schedules packets into
future dates like a calendar. It consists of multiple FIFO queues where only
one of the queues is active. The active queue is either rotated at time
intervals or when the active queue is empty.
*** Attributes:
**** Optimized for hardware
**** Efficiency: O(1)
**** Work Conserving: yes, using a logical CQ
**** Supports Shaping: yes
**** Unit of Scheduling: Packets
**** Programmable: yes, on enqueue
** [ ] DRR/WDRR: Deficit Round Robin / Weighted DRR
*** The DRR scheduler is a RR that adds deficit counters in bytes to each queue.
In each round, the scheduler adds a quantum size in bytes to     the deficit
counters. It then only dequeues a packet from the queue if the deficit counter
has enough bytes to dequeue the packet. This arrangement makes sure that the
fairness of queues/flows also respects packet sizes. The WDRR adds weights to
the queues that the scheduler uses to multiply the quantum before adding it to
the deficit counters to add priority to a queue/flow.
*** Attributes:
**** Optimized for hardware
**** Efficiency: O(1)
**** Work Conserving: yes
**** Supports Shaping:
**** Unit of Scheduling: packets
**** Programmable: no
